### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by NikoVonLas** [meeting-guide/print#2]
Demo not working, where i can see demo result?

I have an idea for our local site - meetings pdf in IP(information prospect) format, i think thats great design for meeting list.

**Comment by joshreisner** [comment]
Hi @NikoVonLas this project isn't going anywhere, and I'm about to remove it.

Good luck with your endeavors and please share any results on tiaa-forum.org, there is lots of interest there in finding a good PDF solution
